-- CLAUSULA UPDATE:

-- Update serve para atualizar valores:

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT NOME, EMAIL
FROM CLIENTE;

-- Update deve ser usado sempre acompanhado do WHERE, para que não haja alteração nos registros errados.

SELECT * FROM CLIENTE
WHERE NOME = 'JOAO';

UPDATE CLIENTE
SET EMAIL = 'JOAO@IG.COM.BR'
WHERE NOME = 'JOAO';

UPDATE CLIENTE
SET EMAIL = 'CELIA@IG.COM.BR'
WHERE NOME = 'CELIA';

UPDATE CLIENTE
SET EMAIL = 'JORGE@HOTMAIL.COM'
WHERE NOME = 'JORGE';

UPDATE CLIENTE
SET EMAIL = 'ANA@HOTMAIL.COM'
WHERE NOME = 'ANA';

UPDATE CLIENTE
SET EMAIL = 'CARLA@HOTMAIL.COM'
WHERE NOME = 'CARLA';

SELECT NOME, EMAIL
FROM CLIENTE;